version: '3'
services:
  bookmark1:
    build: .
    image: bookmark-app:latest
    environment:
      - APP_NAME=bookmark1
    ports:
      - '3001:3000'
    networks:
      - bookmark-network

  bookmark2:
    image: bookmark-app:latest
    environment:
      - APP_NAME=bookmark2
    ports:
      - '3002:3000'
    networks:
      - bookmark-network

  bookmark3:
    image: bookmark-app:latest
    environment:
      - APP_NAME=bookmark3
    ports:
      - '3003:3000'
    networks:
      - bookmark-network

networks:
  bookmark-network:
    external: true
